src/accounts/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.conf.urls import patterns, url
from django.utils.translation import ugettext as _

from accounts.forms import PasswordResetFormEdited, \
    SetPasswordFormEdited
from event.functions import get_fb_app_id

urlpatterns = patterns('',
    url(r'^message/(?P<code>[-\w]+)/$', 'accounts.views.message', name='message'),
    url('^register/', CreateView.as_view(
            template_name='accounts/register.html',
            form_class=UserCreationForm,
            success_url='/'
    ),name="register"),
    url(r'^get-or-create-user-with-fb/', 'accounts.views.get_or_create_user_with_fb', name='get_or_create_user_with_fb'),
)

urlpatterns += patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', {
        'template_name': 'accounts/login.html',
        'extra_context': {
            'page': {
                'title': _('Log in'),
            },
            'FB_APP_ID': get_fb_app_id(),
        }
    }, name='login'),
    url(r'^logout/$', 'logout', {
        'next_page': '/',
    }, name='logout'),
    url(r'^profile/password/reset/$', 'password_reset', {
        'template_name': 'accounts/page_form.html',
        'password_reset_form': PasswordResetFormEdited,
        'post_reset_redirect':'/accounts/message/password_reset/',
        'email_template_name': 'accounts/email_reset.html',
        'extra_context': {
            'page': {
                'title': _('Reset password'),
            },
        }
    }, name='password_reset'),
    url(r'^profile/password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'password_reset_confirm', {
            'template_name': 'accounts/page_form.html',
            'set_password_form': SetPasswordFormEdited,
            'post_reset_redirect': '/accounts/message/password_reset_confirm/',
        }, 'password_reset_confirm',),
)

src/gogo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from gogo import settings

urlpatterns = [
    url(r'^panel/', 'event.views.show_panel', name='show_panel'),
    url(r'^evento/', include('event.urls', namespace='event')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls', namespace='main')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm, SetPasswordForm


class PasswordChangeFormEdited(PasswordChangeForm):
    meta = {'title': _('Change password'), 'button': _('Save'), 'action': '',
            'form_class': 'col-lg-8 col-lg-offset-2', 'header_class': 'header-form-profile'}

    def __init__(self, *args, **kwargs):
        super(PasswordChangeFormEdited, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': self.fields['old_password'].label})
        self.fields['new_password1'].widget.attrs.update(
            {'class': 'form-control input_reset_password', 'placeholder': self.fields['new_password1'].label})
        self.fields['new_password2'].widget.attrs.update(
            {'class': 'form-control input_reset_password', 'placeholder': self.fields['new_password2'].label})


class PasswordResetFormEdited(PasswordResetForm):
    meta = {'title': _('Reset password'), 'button': _('Reset'), 'action': '',
            'form_class': 'col-lg-8 col-lg-offset-2', 'header_class': 'header-form-profile'}

    def __init__(self, *args, **kwargs):
        super(PasswordResetFormEdited, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control input_reset_password', 'placeholder': self.fields['email'].label})


class SetPasswordFormEdited(SetPasswordForm):
    meta = {'title': _('Reset password'), 'button': _('Save'), 'action': '',
            'form_class': 'col-lg-8 col-lg-offset-2', 'header_class': 'header-form-profile'}

    def __init__(self, *args, **kwargs):
        super(SetPasswordFormEdited, self).__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs.update({'class': 'form-control form-first input_reset_password',
                                                          'placeholder': self.fields['new_password1'].label})
        self.fields['new_password2'].widget.attrs.update(
            {'class': 'form-control form-last input_reset_password', 'placeholder': self.fields['new_password2'].label})


def add_class(form, fields):
    for field in fields:
        form.fields[field].widget.attrs.update(
            {
                'class': 'form-control form-first username_login',
                'placeholder': form.fields[field].label
            }
        )


class UserForm(forms.Form):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')


class FacebookUserForm(forms.Form):
    id = forms.CharField(max_length=100)
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)

src/accounts/views.py
import json

from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from django.utils.translation import ugettext as _

from accounts.forms import *
from accounts.functions import get_or_create_user_with_fb_util, FOUND, FOUND_INACTIVE


def message(request, code):
    if code == 'password_reset':
        message = _(
            '<strong>We have sent you an email!</strong> Please, follow the instructions to reset your password.')
        # messages.add_message(request, messages.INFO, message)
        return render(request, 'accounts/echo.html', locals())
        # return redirect(reverse('accounts:password_reset'))

    if code == 'password_reset_confirm':
        messages.add_message(request, messages.INFO, _(
            '<strong>Success!</strong> You have changed your password.'))
        return redirect(reverse('accounts:login'))

    if code == 'password_change_done':
        messages.add_message(request, messages.INFO, _(
            '<strong>Success!</strong> You have changed your password.'))
        return redirect(reverse('accounts:password_change'))

    return redirect(reverse('accounts:profile_edit'))


@csrf_exempt
def get_or_create_user_with_fb(request):
    data = request.POST['data']
    json_loads = json.loads(data)

    facebook_user_form = FacebookUserForm(json_loads)
    if not facebook_user_form.is_valid():
        response_data = {
            'result': 'error',
            'message': 'fb user incorrect',
        }
        return HttpResponse(json.dumps(response_data), content_type="application/json")

    fb_id = facebook_user_form.cleaned_data['id']

    response, user = get_or_create_user_with_fb_util(facebook_user_form=facebook_user_form)

    if response == FOUND:
        user = authenticate(username=user.username, password=fb_id)
        login(request, user)
        response_data = {
            'result': 'success',
            'message': 'welcome ' + user.first_name,
            'redirect_to': reverse('show_panel')
        }
    elif response == FOUND_INACTIVE:
        response_data = {'result': 'warning', 'message': 'your user account is being validating'}
    else:
        user = authenticate(username=user.username, password=fb_id)
        login(request, user)
        response_data = {
            'result': 'warning',
            'message': 'Ok!, welcome again ',
            'redirect_to': reverse('event:event_create')
        }

    return HttpResponse(json.dumps(response_data), content_type="application/json")

src/accounts/templates/accounts/base_profile_edit.html
{% extends 'app/layout.html' %}
{% load i18n %}
{% block content %}

<div class="btn-group pull-right" style="margin-top:25px;">
	<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<span class="glyphicon glyphicon-cog"></span>
	</button>

	<ul class="dropdown-menu">
		<li{% if page.code == 'profile_edit' %} class="active"{% endif %}>
			<a href="{% url 'accounts:profile_edit' %}">{% trans "Edit profile" %}</a>
		</li>
		<li{% if page.code == 'password_edit' %} class="active"{% endif %}>
			<a href="{% url 'accounts:password_change' %}">{% trans "Change password" %}</a>
		</li>
	</ul>
</div>

{% include "snippets/form_complete.html" with form=form %}

{% endblock %}

src/accounts/templates/accounts/echo.html
{% extends 'panels/layout.html' %}
{% load i18n %}
{% block content %}

<div class="contenedor_form paypal_request">
	<div class="inner cover landing">
		<h3 class="home_subtitle">{{ message|safe }}</h3>
	</div>
</div>

{% endblock %}

src/accounts/templates/accounts/email_reset.html
{% load i18n %}
{% autoescape off %}
    {% blocktrans %}You're receiving this e-mail because you requested a password reset
        for your user account at {{ site_name }}{% endblocktrans %}.

    {% trans "Please go to the following page and choose a new password:" %}
    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
    {% endblock %}
    {% trans "Your username, in case you've forgotten:" %} {{ user.username }}

    {% trans "Thanks for using our site!" %}

    {% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

src/accounts/templates/accounts/form.html
{% if form.non_field_errors %}
    <div class="alert alert-danger">
    {% for error in form.non_field_errors %}
        <p>{{ error }}</p>
    {% endfor %}
    </div>
{% endif %}

{% for field in form %}
{% comment %}
    <div class="form-group {% if field.errors %} has-error{% endif %}">
{% endcomment %}
    {% if field.errors %}
    <div class="has-error">
    {% endif %}

    {{ field }}
    {% for error in field.errors %}
        <span class="help-block">{{ error }}</span>
    {% endfor %}

    {% if field.errors %}
        </div>
    {% endif %}
{% endfor %}

src/accounts/templates/accounts/login.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="ThemeBucket">
    <link rel="shortcut icon" href="#" type="image/png">

    <title>Login</title>

    <link href="{% static 'event/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'event/css/style-responsive.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="{% static 'event/js/html5shiv.js'%}"></script>
    <script src="{% static 'event/js/respond.min.js'%}"></script>
    <![endif]-->
</head>

<body class="login-body">

<div class="container">


    <form id="form_login" class="form-signin" role="form" action="." method="post">
        {% if user.is_authenticated %}
            <h3>{% trans "You are logged in as" %} <strong>{{ user.username }}</strong>. <a
                    href="{% url 'accounts:logout' %}">{% trans 'Logout.' %}</a></h3>
        {% else %}

            <div class="form-signin-heading text-center">
                <h1 class="sign-title">Ingresar</h1>
                <img src="{% static 'main/img/yovoy-dark.png' %}" alt="" width="50%"/>
            </div>
            <div class="login-wrap">
                <button class="btn btn-login btn-block" type="button" onclick="fb_login(afterFb_me)">
                    Login with <i class="fa fa-facebook"></i>
                </button>
            </div>
        {% endif %}
    </form>

</div>
<div id="fb-root"></div>

<!-- Placed js at the end of the document so the pages load faster -->

<!-- Placed js at the end of the document so the pages load faster -->
<script src="{% static 'event/js/jquery-1.10.2.min.js' %}"></script>
<script src="{% static 'event/js/bootstrap.min.js' %}"></script>
<script src="{% static 'event/js/modernizr.min.js' %}"></script>
<script>var fbAppId = '{{ FB_APP_ID }}';</script>
<script src="{% static 'main/js/fb/fb.js' %}"></script>
<script>
    function afterFb_me(fbResponse) {
        $.post('/accounts/get-or-create-user-with-fb/', {data: JSON.stringify(fbResponse)}, function (response) {
            url = window.location.href
            var redirectTo = url.indexOf("next=");
            if(redirectTo!=-1){
                window.location.href = url.substr(redirectTo+5);
            }else {
                alert('intenta de nuevo porfavor');
            }
        });
    }
</script>
</body>
</html>

src/accounts/templates/accounts/page_form.html
{% extends 'app/layout2.html' %}
{% load i18n %}

{% block scripts %}
{% endblock %}

{% block content %}

    <form class="form-signin reset_pass" role="form" action="." method="post">
        <h2 class="form-signin-heading" style="margin-bottom: 25px;">
            {{ form.meta.title }}
        </h2>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="alert alert-success">
                {% elif message.tags == 'warning' %}
                    <div class="alert">
                {% elif message.tags == 'error' %}
                    <div class="alert alert-danger">
                {% else %}
                    <div class="alert alert-info">
                {% endif %}
                {{ message|safe }}
                </div>
            {% endfor %}
        {% endif %}

        {% csrf_token %}
        {% include "accounts/form.html" with form=form %}
        <button class="btn btn-md btn-primary btn-block btn_general" type="submit" style="margin-top: 15px;">{{ form.meta.button }}</button>

    </form>



{% endblock %}

src/accounts/templates/accounts/register.html
{% extends 'panels/layout.html' %}
{% load i18n %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="contenedor_form">
            <div class="inner cover landing">
                <h3 class="home_subtitle">
                    {% trans "You are logged in as" %} <strong>{{ user.username }}</strong>. <a
                        href="{% url 'accounts:logout' %}">{% trans 'Logout.' %}</a>
                </h3>
            </div>
        </div>
    {% else %}
        <form role="form" action="." method="post" enctype="multipart/form-data">

            <h2 class="form-signin-heading" style="margin-bottom: 25px; color: #2f3539;">
                {% trans "Apply for an account" %}
            </h2>

            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <div class="alert alert-success">
                    {% elif message.tags == 'warning' %}
                        <div class="alert">
                    {% elif message.tags == 'error' %}
                        <div class="alert alert-danger">
                    {% else %}
                        <div class="alert alert-info">
                    {% endif %}
                {{ message|safe }}
                </div>
                {% endfor %}
            {% endif %}
            {% csrf_token %}

            {% include "hock/form.html" with form=form %}
            <input type="reset" value="Reset Fields"/>
            <button class="btn btn-md btn-primary btn-block btn-sign-in" type="submit"
                    style="margin-top: 15px;">{% trans 'Request account' %}</button>
        </form>
    {% endif %}
{% endblock %}