src/accounts/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.conf.urls import patterns, url
from django.utils.translation import ugettext as _

from accounts.forms import PasswordResetFormEdited, \
    SetPasswordFormEdited
from event.functions import get_fb_app_id

urlpatterns = patterns('',
    url(r'^message/(?P<code>[-\w]+)/$', 'accounts.views.message', name='message'),
    url('^register/', CreateView.as_view(
            template_name='accounts/register.html',
            form_class=UserCreationForm,
            success_url='/'
    ),name="register"),
    url(r'^get-or-create-user-with-fb/', 'accounts.views.get_or_create_user_with_fb', name='get_or_create_user_with_fb'),
)

urlpatterns += patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', {
        'template_name': 'accounts/login.html',
        'extra_context': {
            'page': {
                'title': _('Log in'),
            },
            'FB_APP_ID': get_fb_app_id(),
        }
    }, name='login'),
    url(r'^logout/$', 'logout', {
        'next_page': '/',
    }, name='logout'),
    url(r'^profile/password/reset/$', 'password_reset', {
        'template_name': 'accounts/page_form.html',
        'password_reset_form': PasswordResetFormEdited,
        'post_reset_redirect':'/accounts/message/password_reset/',
        'email_template_name': 'accounts/email_reset.html',
        'extra_context': {
            'page': {
                'title': _('Reset password'),
            },
        }
    }, name='password_reset'),
    url(r'^profile/password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'password_reset_confirm', {
            'template_name': 'accounts/page_form.html',
            'set_password_form': SetPasswordFormEdited,
            'post_reset_redirect': '/accounts/message/password_reset_confirm/',
        }, 'password_reset_confirm',),
)

src/event/urls.py
from django.conf.urls import patterns
from django.conf.urls import url
urlpatterns = patterns('event.views',
    url(r'^(?P<event_nick>\w+)/panel/$', 'home', name='home'),
    url(r'^nuevo/', 'event_create', name='event_create'),
    url(r'^panel/', 'show_panel', name='show_panel'),
    url(r'^(?P<event_nick>\w+)/editar/', 'event_edit', name='event_edit'),
    url(r'^(?P<event_nick>\w+)/scheme/', 'scheme', name='scheme'),
    url(r'^(?P<event_nick>\w+)/registers/', 'registers_json', name='registers_json'),
    url(r'^upload-image/', 'upload_image', name='upload_image'),
    url(r'^save-ticket/', 'save_ticket', name='save_ticket'),
    url(r'^delete-ticket/', 'delete_ticket', name='delete_ticket'),
    url(r'^(?P<event_nick>\w+)/inscritos/', 'registers', name='registers'),
    url(r'^(?P<event_nick>\w+)/registers-jqgrid/', 'registers_jqgrid', name='registers_jqgrid'),
    url(r'^(?P<event_nick>\w+)/registers-jqgrid-edit/', 'registers_jqgrid_edit', name='registers_jqgrid_edit'),

)

src/gogo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from gogo import settings

urlpatterns = [
    url(r'^panel/', 'event.views.show_panel', name='show_panel'),
    url(r'^evento/', include('event.urls', namespace='event')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls', namespace='main')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.conf.urls import patterns
from django.conf.urls import url


urlpatterns = patterns('main.views',
                       url(r'^(?P<event_nick>.+)/register/$', 'register', name='register'),
                       url(r'^(?P<event_nick>.+)/registers/$', 'filter_register', name='filter_register'),
                       url(r'^(?P<event_nick>.+)/$', 'show_event', name='show_event'),
                       url(r'^$', 'home', name='home'),
                       )

src/event/models.py
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from django.db import models


class Institution(models.Model):
    name = models.CharField(_('name'), max_length=100, blank=False, null=False)
    fb_id = models.CharField(max_length=100, blank=True, null=True)
    lat = models.FloatField(default=0)
    lng = models.FloatField(default=0)
    is_active = models.BooleanField(_('is active'), default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Event(models.Model):
    name = models.CharField(_('name'), max_length=100, blank=False, null=False)
    description = models.TextField(_('description'), blank=True, null=True)
    nick = models.SlugField(_('nick'), max_length=100, blank=False, null=False, unique=True)
    domain = models.URLField(_('domain'), null=True, blank=True)
    address = models.CharField(_('address'), max_length=200, blank=True, null=True)
    logo = models.ImageField(_('logo'), upload_to='images', blank=True, null=True)
    slogan = models.CharField(_('slogan'), max_length=200, blank=True, null=True)
    facebook = models.URLField(max_length=255, blank=True, null=True)
    twitter = models.URLField(max_length=255, blank=True, null=True)
    map_point = models.CharField(max_length=40)
    map_place = models.CharField(max_length=250)
    start = models.DateField(_('start'), null=False)
    start_time = models.TimeField(_('at'), null=True, blank=True)
    end = models.DateField(_('end'), null=True, blank=True)
    end_time = models.TimeField(_('to'), null=True, blank=True)
    is_payed = models.BooleanField(_('use tickets'), default=False)
    owner = models.ForeignKey(User, unique=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nick


Event.page_scheme = property(lambda e: PageScheme.objects.get_or_create(event=e)[0])
Event.tickets_public = property(lambda e: Ticket.objects.filter(event=e, is_active=True, is_public=True))
Event.tickets_all = property(lambda e: Ticket.objects.filter(event=e, is_active=True))
Event.person_details = property(lambda e: EventPersonDetail.objects.get_or_create(event=e)[0])


# class PersonRequest(models.Model):

class PageScheme(models.Model):
    event = models.ForeignKey(Event)
    theme = models.CharField(max_length=20, blank=True, null=True)
    scheme = models.TextField(blank=True, null=True)
    main = models.TextField(blank=True, null=True)
    nav = models.TextField(blank=True, null=True)
    footer = models.TextField(blank=True, null=True)


class Ticket(models.Model):
    name = models.CharField(_('name'), max_length=100, blank=False, null=False)
    description = models.CharField(_('description'), max_length=100, blank=True, null=True)
    quantity = models.IntegerField(_('quantity'), default=0)
    cost = models.IntegerField(_('cost'), blank=False, null=False)
    is_active = models.BooleanField(_('active'), default=True)
    is_public = models.BooleanField(_('public'), default=True)
    event = models.ForeignKey(Event)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Person(models.Model):
    first_name = models.CharField(max_length=50, null=False, blank=False)
    last_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    fb_id = models.CharField(max_length=50)
    user = models.OneToOneField(User, blank=True, null=True)
    facebook = models.URLField(max_length=255, blank=True, null=True)
    linkedin = models.URLField(max_length=255, blank=True, null=True)
    twitter = models.URLField(max_length=255, blank=True, null=True)
    is_active = models.BooleanField(_('is active'), default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name + " " + self.last_name


User.person = property(lambda s: Person.objects.get_or_create(user=s)[0])


class PersonInstitution(models.Model):
    person = models.ForeignKey(Person)
    institution = models.ForeignKey(Institution)

    code = models.CharField(max_length=20, blank=True, null=True)
    is_active = models.BooleanField(_('is active'), default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class PersonDetail(models.Model):
    man = _('man')
    woman = _('woman')

    SEX_CHOICES = (
        (1, man),
        (2, woman),
    )

    person = models.ForeignKey(Person)
    dni = models.CharField(_('DNI'), max_length=20, blank=True, null=True)
    document = models.CharField(max_length=50, null=True, blank=True)
    date_birth = models.DateField(_('Date Birth'), blank=True, null=True)
    sex = models.IntegerField(_('Sex'), blank=True, null=True, choices=SEX_CHOICES)
    profession = models.CharField(_('Profession'), max_length=100, null=True, blank=True)

Person.detail = property(lambda p: Person.objects.get_or_create(person=p)[0])


class EventPersonDetail(models.Model):
    event = models.ForeignKey(Event)
    is_dni = models.BooleanField(_('Request DNI'), default=False)
    is_date_birth = models.BooleanField(_('Request Date Birth'), default=False)
    is_sex = models.BooleanField(_('Request Sex'), default=False)
    is_institution = models.BooleanField(_('Request Institution'), default=False)
    is_code = models.BooleanField(_('Request Institution Code'), default=False)
    is_profession = models.BooleanField(_('Request Profession'), default=False)


class Register(models.Model):
    STATUS_CHOICES = (
        (1, _('pending')),
        (2, _('confirmed')),
    )

    person = models.ForeignKey(Person)
    person_institution = models.ForeignKey(PersonInstitution, blank=True, null=True)
    ticket = models.ForeignKey(Ticket, blank=True, null=True)
    event = models.ForeignKey(Event, blank=False, null=False)
    voucher = models.CharField(_('voucher'), max_length=100, blank=True, null=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    is_active = models.BooleanField(_('is active'), default=False)
    has_material = models.BooleanField(_('has material'), default=False)
    note = models.TextField(blank=True, null=True)
    note2 = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


def content_file_name(instance, filename):
    return '/'.join(['events', instance.event.nick, filename])


class EventImage(models.Model):
    event = models.ForeignKey(Event, related_name='images')
    image = models.ImageField(upload_to=content_file_name)

src/event/forms.py
from django import forms
from django.utils.translation import ugettext as _

from event.functions import add_class, add_class_date_picker, add_class_time_picker
from event.widgets import AvatarWidgetNoLink

__author__ = 'bicho'

from django.forms import ModelForm

from event.models import Event, EventImage, Ticket, Person


class EventForm(ModelForm):
    form_meta = {
        'title': _('new event'),
        'help_collapse': True,
    }
    start = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y',))
    start_time = forms.TimeField(widget=forms.TimeInput(format='%I:%M %p'), input_formats=('%I:%M %p',))
    end = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y',), required=False)
    end_time = forms.TimeField(widget=forms.TimeInput(format='%I:%M %p'), input_formats=('%I:%M %p',), required=False)
    map_point = forms.CharField(error_messages={"required": "This field required you select a point on the map."})

    class Meta:
        model = Event
        exclude = ('owner', 'places', 'logo', 'slogan', 'theme', 'domain')

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        add_class(self, ['name', 'address', 'nick', 'start_time', 'description'])
        add_class_date_picker(self, ['start', 'end'])
        add_class_time_picker(self, ['start_time', 'end_time'])

        self.fields['nick'].widget.attrs.update(
            {
                'placeholder': _('hashtag'),
            }
        )


class EventEditForm(ModelForm):
    form_meta = {
        'title': _('new event'),
        'help_collapse': True,
    }
    start = forms.DateField(label=_('start'), widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y',))
    start_time = forms.TimeField(label=_('at'), widget=forms.TimeInput(format='%I:%M %p'), input_formats=('%I:%M %p',))
    end = forms.DateField(label=_('end'), widget=forms.DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y',),
                          required=False)
    end_time = forms.TimeField(label=_('to'), widget=forms.TimeInput(format='%I:%M %p'), input_formats=('%I:%M %p',),
                               required=False)
    map_point = forms.CharField(error_messages={"required": "This field required you select a point on the map."})

    class Meta:
        model = Event
        exclude = (
            'owner', 'nick', 'places', 'theme')
        widgets = {
            'logo': AvatarWidgetNoLink,
        }

    def __init__(self, *args, **kwargs):
        super(EventEditForm, self).__init__(*args, **kwargs)
        add_class(self,
                  ['name', 'start_time', 'description', 'address', 'logo', 'slogan', 'facebook', 'twitter', 'domain'])
        add_class_date_picker(self, ['start', 'end'])
        add_class_time_picker(self, ['start_time', 'end_time'])


class EventImageForm(ModelForm):
    class Meta:
        model = EventImage
        fields = '__all__'


class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ('id', 'event', 'name', 'quantity', 'cost')


class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = ('first_name', 'last_name', 'email')

src/event/templates/event/base_form.html
{% extends 'event/layout_event.html' %}
{% load static %}
{% block content %}
    <!--body wrapper start-->
    <div class="row">
        <div class="col-sm-12">
            {% include 'event/hooks/form_vertical.html' with form=form %}
        </div>
    </div>

{% endblock %}

src/event/templates/event/event_configuration.html
{% extends 'event/layout_event.html' %}
{% load static %}
{% block content %}
    <!--body wrapper start-->
    <div class="wrapper">
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    {% include 'event/hooks/form_vertical.html' with form=form %}

                </section>
            </div>
        </div>
    </div>
{% endblock %}

src/event/templates/event/event_form.html
{% extends layout %}
{% load static %}
{% load i18n %}
{% block content %}
    <style>
        .default-buttons{
            position: fixed;
            bottom: 50px;
            right: 10%;
        }
    </style>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <section class="panel">
                <header class="panel-heading">
                    {{ form.form_meta.title }}
                </header>
                <div class="panel-body">
                    <div class="widget-container">
                        <div class="stepy-tab">
                        </div>
                        <form id="default" class="form-horizontal adminex-form" method="post" action=".">
                            <fieldset title="{% trans 'Information' %}">
                                <legend>{% trans 'general' %}</legend>
                                {% csrf_token %}
                                {% include 'event/hooks/field_horizontal.html' with field=form.name %}
                                {% include 'event/hooks/field_horizontal.html' with field=form.nick %}
                                {% include 'event/hooks/field_date_time_inline.html' with field_date=form.start field_time=form.start_time is_advanced=False %}
                                <div class="pull-right" style="margin-top: -35px">
                                    <a id="end_link" href="#">{% trans 'is your event for more than one day' %}<i
                                            class="fa fa-question"></i></a>
                                </div>
                                <br/>
                                {% include 'event/hooks/field_date_time_inline.html' with field_date=form.end field_time=form.end_time is_advanced=True %}
                            </fieldset>
                            <fieldset title="{% trans 'Where' %}">
                                <legend>{% trans 'is on the map?' %}</legend>
                                {% include 'event/hooks/field_horizontal.html' with field=form.address %}
                                {% include 'event/hooks/field_map_point.html' with field_place=form.map_place field_point=form.map_point %}
                            </fieldset>
                            <fieldset title="{% trans 'Tickets' %}">
                                <legend>{% trans 'payed or not' %}</legend>
                                {% include 'event/hooks/field_boolean.html' with field=form.is_payed %}
                                <div class="form-group" style="border-bottom: none; display: none">
                                    <label class="col-sm-2 control-label col-lg-2"
                                           for="inputSuccess">{% trans 'ticket' %} </label>

                                    <div class="col-lg-10" id="tickets">
                                        <div class="row ticketItem" style="margin-bottom: 10px">
                                            <div class="col-lg-3">
                                                <input type="text" class="form-control" placeholder="{% trans 'name' %}"
                                                       name="name[]">
                                            </div>
                                            <div class="col-lg-3">
                                                <input type="number" class="form-control" placeholder="{% trans 'cost' %}"
                                                       name="cost[]">
                                            </div>
                                            <div class="col-lg-3">
                                                <input type="number" class="form-control"
                                                       placeholder="{% trans 'quantity' %}"
                                                       name="quantity[]">
                                            </div>
                                            <div class="col-lg-1">
                                                <a style="display: none;" href="#"
                                                   onclick="$(this).parents('.ticketItem').remove();return false;">
                                                    <i class="fa fa-minus-circle"></i>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group" style="display: none">
                                    <div class="row">
                                        <div class="col-md-2 col-md-offset-10" style="margin-top: -35px">
                                            <a id="oneMoreTicketLink" href="#">{% trans 'one more' %} <i
                                                    class="fa fa-question"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </fieldset>
                            <fieldset title="{% trans 'Final Step' %}">
                                <legend>{% trans 'Final Step Information' %}</legend>
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <p>{% trans 'Congratulations This is the Final Step' %}</p>
                                    </div>
                                </div>
                            </fieldset>
                            <button class="btn btn-info finish">
                                Finish
                            </button>
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock %}
{% block more_scripts %}
    <link href="{% static 'event/css/jquery.stepy.css' %}" rel="stylesheet">
    {% include 'event/scripts/datepicker.html' %}
    {% include 'event/scripts/timepicker.html' %}
    {% include 'event/scripts/icheck.html' %}
    <script src="{% static 'event/js/jquery.stepy.js' %}"></script>
    <script>
        $(document).ready(function(){
            var endDateParent = $('#id_end').parents('.form-group');
            endDateParent.css('display', 'none');
            endDateParent.css('margin-top', '-25px');

            $('#default').stepy({
                backLabel: '{% trans 'Previous' %}',
                block: true,
                nextLabel: '{% trans 'Next' %}',
                titleClick: true,
                titleTarget: '.stepy-tab'
            });


            $('#default-next-0, #default-title-1, #default-back-2').on('click', function () {
                google.maps.event.trigger(jCoreGoogleMap.maps.mapmapPoint.map, 'resize');
            })

            if($('#is_payed_yes').is(':checked')){
                $('#tickets').parents('.form-group').toggle('show');
                $('#oneMoreTicketLink').parents('.form-group').toggle('show');
            }
        });

        $('#end_link').click(function () {
            var endLinkIcon = $('#end_link').find('i');
            var endFormGroup = $('#id_end').parents('.form-group');
            var startFormGroup = $('#id_start').parents('.form-group');
            if (endFormGroup.is(':visible')) {
                startFormGroup.css('border-bottom', '1px solid #eff2f7');
                endLinkIcon.addClass('fa-question');
                endLinkIcon.removeClass('fa-exclamation');
            } else {
                startFormGroup.css('border-bottom', '0px');
                endLinkIcon.removeClass('fa-question');
                endLinkIcon.addClass('fa-exclamation');
            }
            endFormGroup.toggle('slow');
            return false;
        });
        $('#oneMoreTicketLink').click(function () {
            $ticketItem = $('.ticketItem').first().clone();
            $ticketItem.find('.fa-minus-circle').parents('a').show();
            $ticketItem.find('input').each(function(){$(this).val('')});
            $('#tickets').append($ticketItem);
            return false;
        });
        $('#is_payed_yes,#is_payed_no').on('ifChecked', function (event) {
            if($('#is_payed_yes').is(':checked')){
                $('#tickets').parents('.form-group').toggle('show');
                $('#oneMoreTicketLink').parents('.form-group').toggle('show');
            }
        });
        $('#id_nick').focus(function () {
            var $idNick = $('#id_nick');

            if ($idNick.val() == '') {
                $idNick.val(generateShortName($('#id_name').val()));
            }
        });


    </script>
{% endblock %}

src/event/templates/event/event_form_edit.html
{% extends layout %}
{% load static %}
{% load i18n %}
{% block content %}
    <!--body wrapper start-->
    <div class="row">
        <div class="col-sm-12">
            <section class="panel">
                <header class="panel-heading">
                    {% trans 'information' %}
                </header>
                <div class="panel-body">
                    <form class="form-horizontal adminex-form" method="post" action="." enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'event/hooks/field_horizontal.html' with field=form.name %}
                        {% include 'event/hooks/field_date_time_inline.html' with field_date=form.start field_time=form.start_time is_advanced=False %}
                        {% include 'event/hooks/field_horizontal.html' with field=form.slogan %}
                        {% include 'event/hooks/field_horizontal.html' with field=form.logo %}
                        {% include 'event/hooks/field_horizontal.html' with field=form.description %}
{#                        {% include 'event/hooks/field_horizontal_span.html' with field=form.nick span_text='.yovoy.pe' %}#}
                        {% include 'event/hooks/field_horizontal.html' with field=form.domain %}
                        {% include 'event/hooks/field_horizontal.html' with field=form.address %}


                        <div class="pull-right" style="margin-top: -35px">
                            <a id="end_link" href="#">{% trans 'use end date' %} <i class="fa fa-question"></i></a>
                        </div>
                        <br/>

                        {% include 'event/hooks/field_date_time_inline.html' with field_date=form.end field_time=form.end_time is_advanced=True %}
                        <div class="form-group" style="display: none">
                            <div class="row">
                                <div class="col-md-2 col-md-offset-10" style="margin-top: -35px">
                                    <a id="oneMoreAttendanceTypeLink" href="#">one more <i
                                            class="fa fa-question"></i></a>
                                </div>
                            </div>
                        </div>
                        {% include 'event/hooks/field_map_point.html' with field_place=form.map_place field_point=form.map_point %}
                        {% include 'event/hooks/field_horizontal.html' with field=form.facebook %}
                        {% include 'event/hooks/field_horizontal.html' with field=form.twitter %}
                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button type="submit" class="btn btn-primary">{% trans 'update' %}</button>
                            </div>
                        </div>


                    </form>
                </div>
            </section>
        </div>
    </div>

{% endblock %}
{% block more_scripts %}
    {% include 'event/scripts/datepicker.html' %}
    {% include 'event/scripts/timepicker.html' %}
    {% include 'event/scripts/icheck.html' %}
    <script>
        $(function () {
            var endDateParent = $('#id_end').parents('.form-group');
            endDateParent.css('display', 'none');
            endDateParent.css('margin-top', '-25px');
        });

        $('#end_link').click(function () {
            var endLinkIcon = $('#end_link').find('i');
            var endFormGroup = $('#id_end').parents('.form-group');
            var startFormGroup = $('#id_start').parents('.form-group');
            if (endFormGroup.is(':visible')) {
                startFormGroup.css('border-bottom', '1px solid #eff2f7');
                endLinkIcon.addClass('fa-question');
                endLinkIcon.removeClass('fa-exclamation');
            } else {
                startFormGroup.css('border-bottom', '0px');
                endLinkIcon.removeClass('fa-question');
                endLinkIcon.addClass('fa-exclamation');
            }
            endFormGroup.toggle('slow');
            return false;
        });
        $('#oneMoreAttendanceTypeLink').click(function () {
            $ticketItem = $('.ticketItem').first().clone();
            $ticketItem.find('.fa-minus-circle').parents('a').show();
            $('#tickets').append($ticketItem);
            return false;
        });
        $('#is_payed_yes,#is_payed_no').on('ifChecked', function (event) {
            $('#tickets').parents('.form-group').toggle('show');
            $('#oneMoreAttendanceTypeLink').parents('.form-group').toggle('show');
        });

    </script>
{% endblock %}

src/event/templates/event/layout_event.html
{% extends 'event/layout.html' %}
{% load event_extras %}
{% load i18n %}
{% block nav %}
    <!-- left side start-->
    <div class="left-side sticky-left-side">

        <!--logo and iconic logo start-->
        <div class="logo">
            <a href="#">{{ event.nick }}</a>
        </div>

        <div class="logo-icon text-center">
            <a href="#" style="color: #fff">{{ event.nick }}</a>
        </div>
        <!--logo and iconic logo end-->


        <div class="left-side-inner">

            <!--sidebar nav start-->
            {% include 'event/sections/navigation.html' %}
            <!--sidebar nav end-->
        </div>
    </div>
    <!-- left side end-->
{% endblock %}

src/event/templates/event/panel.html
{% extends 'event/layout.html' %}
{% load static %}
{% load i18n %}
{% block content %}
    <div class="container">
        <div class="col-md-8 col-md-offset-2">
            <div class="wrapper">
                <div class="row">
                    <div class="col-sm-12">
                        <section class="panel">

                            <div class="tools pull-right" style="padding-right: 10px;padding-top: 12px;height: 30px;">
                                <a href="{% url 'event:event_create' %}">{% trans 'create event' %}</a>
                            </div>
                            <header class="panel-heading">
                                {% trans 'MY EVENTS' %}
                            </header>
                            <div class="panel-body">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>{% trans 'nick' %}</th>
                                        <th>{% trans 'name' %}</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for event in events %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ event.nick }}</td>
                                            <td>{{ event.name }}</td>
                                            <td><a href="{% url 'main:show_event' event.nick %}" target="_blank">{% trans 'visit' %}</a>
                                                | <a
                                                        href="{% url 'event:home' event.nick %}">{% trans 'admin' %}</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}