src/gogo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from gogo import settings

urlpatterns = [
    url(r'^panel/', 'event.views.show_panel', name='show_panel'),
    url(r'^evento/', include('event.urls', namespace='event')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls', namespace='main')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.conf.urls import patterns
from django.conf.urls import url


urlpatterns = patterns('main.views',
                       url(r'^(?P<event_nick>.+)/register/$', 'register', name='register'),
                       url(r'^(?P<event_nick>.+)/registers/$', 'filter_register', name='filter_register'),
                       url(r'^(?P<event_nick>.+)/$', 'show_event', name='show_event'),
                       url(r'^$', 'home', name='home'),
                       )

src/event/models.py
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from django.db import models


class Institution(models.Model):
    name = models.CharField(_('name'), max_length=100, blank=False, null=False)
    fb_id = models.CharField(max_length=100, blank=True, null=True)
    lat = models.FloatField(default=0)
    lng = models.FloatField(default=0)
    is_active = models.BooleanField(_('is active'), default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Event(models.Model):
    name = models.CharField(_('name'), max_length=100, blank=False, null=False)
    description = models.TextField(_('description'), blank=True, null=True)
    nick = models.SlugField(_('nick'), max_length=100, blank=False, null=False, unique=True)
    domain = models.URLField(_('domain'), null=True, blank=True)
    address = models.CharField(_('address'), max_length=200, blank=True, null=True)
    logo = models.ImageField(_('logo'), upload_to='images', blank=True, null=True)
    slogan = models.CharField(_('slogan'), max_length=200, blank=True, null=True)
    facebook = models.URLField(max_length=255, blank=True, null=True)
    twitter = models.URLField(max_length=255, blank=True, null=True)
    map_point = models.CharField(max_length=40)
    map_place = models.CharField(max_length=250)
    start = models.DateField(_('start'), null=False)
    start_time = models.TimeField(_('at'), null=True, blank=True)
    end = models.DateField(_('end'), null=True, blank=True)
    end_time = models.TimeField(_('to'), null=True, blank=True)
    is_payed = models.BooleanField(_('use tickets'), default=False)
    owner = models.ForeignKey(User, unique=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nick


Event.page_scheme = property(lambda e: PageScheme.objects.get_or_create(event=e)[0])
Event.tickets_public = property(lambda e: Ticket.objects.filter(event=e, is_active=True, is_public=True))
Event.tickets_all = property(lambda e: Ticket.objects.filter(event=e, is_active=True))
Event.person_details = property(lambda e: EventPersonDetail.objects.get_or_create(event=e)[0])


# class PersonRequest(models.Model):

class PageScheme(models.Model):
    event = models.ForeignKey(Event)
    theme = models.CharField(max_length=20, blank=True, null=True)
    scheme = models.TextField(blank=True, null=True)
    main = models.TextField(blank=True, null=True)
    nav = models.TextField(blank=True, null=True)
    footer = models.TextField(blank=True, null=True)


class Ticket(models.Model):
    name = models.CharField(_('name'), max_length=100, blank=False, null=False)
    description = models.CharField(_('description'), max_length=100, blank=True, null=True)
    quantity = models.IntegerField(_('quantity'), default=0)
    cost = models.IntegerField(_('cost'), blank=False, null=False)
    is_active = models.BooleanField(_('active'), default=True)
    is_public = models.BooleanField(_('public'), default=True)
    event = models.ForeignKey(Event)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Person(models.Model):
    first_name = models.CharField(max_length=50, null=False, blank=False)
    last_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    fb_id = models.CharField(max_length=50)
    user = models.OneToOneField(User, blank=True, null=True)
    facebook = models.URLField(max_length=255, blank=True, null=True)
    linkedin = models.URLField(max_length=255, blank=True, null=True)
    twitter = models.URLField(max_length=255, blank=True, null=True)
    is_active = models.BooleanField(_('is active'), default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name + " " + self.last_name


User.person = property(lambda s: Person.objects.get_or_create(user=s)[0])


class PersonInstitution(models.Model):
    person = models.ForeignKey(Person)
    institution = models.ForeignKey(Institution)

    code = models.CharField(max_length=20, blank=True, null=True)
    is_active = models.BooleanField(_('is active'), default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class PersonDetail(models.Model):
    man = _('man')
    woman = _('woman')

    SEX_CHOICES = (
        (1, man),
        (2, woman),
    )

    person = models.ForeignKey(Person)
    dni = models.CharField(_('DNI'), max_length=20, blank=True, null=True)
    document = models.CharField(max_length=50, null=True, blank=True)
    date_birth = models.DateField(_('Date Birth'), blank=True, null=True)
    sex = models.IntegerField(_('Sex'), blank=True, null=True, choices=SEX_CHOICES)
    profession = models.CharField(_('Profession'), max_length=100, null=True, blank=True)

Person.detail = property(lambda p: Person.objects.get_or_create(person=p)[0])


class EventPersonDetail(models.Model):
    event = models.ForeignKey(Event)
    is_dni = models.BooleanField(_('Request DNI'), default=False)
    is_date_birth = models.BooleanField(_('Request Date Birth'), default=False)
    is_sex = models.BooleanField(_('Request Sex'), default=False)
    is_institution = models.BooleanField(_('Request Institution'), default=False)
    is_code = models.BooleanField(_('Request Institution Code'), default=False)
    is_profession = models.BooleanField(_('Request Profession'), default=False)


class Register(models.Model):
    STATUS_CHOICES = (
        (1, _('pending')),
        (2, _('confirmed')),
    )

    person = models.ForeignKey(Person)
    person_institution = models.ForeignKey(PersonInstitution, blank=True, null=True)
    ticket = models.ForeignKey(Ticket, blank=True, null=True)
    event = models.ForeignKey(Event, blank=False, null=False)
    voucher = models.CharField(_('voucher'), max_length=100, blank=True, null=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    is_active = models.BooleanField(_('is active'), default=False)
    has_material = models.BooleanField(_('has material'), default=False)
    note = models.TextField(blank=True, null=True)
    note2 = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


def content_file_name(instance, filename):
    return '/'.join(['events', instance.event.nick, filename])


class EventImage(models.Model):
    event = models.ForeignKey(Event, related_name='images')
    image = models.ImageField(upload_to=content_file_name)

src/main/forms.py
from django import forms
from event.models import PersonDetail

__author__ = 'bicho'

from django.utils.translation import ugettext as _
from accounts.models import Person
from event.functions import add_class
from django.forms import ModelForm


class PersonForm(ModelForm):
    form_meta = {
        'title': _('new person'),
        'help_collapse': True,
    }

    class Meta:
        model = Person
        fields = ('first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init__(*args, **kwargs)
        add_class(self, ['first_name', 'last_name'])

        if 'instance' in kwargs:
            self.form_meta['title'] = _('edit') + ' ' + _('person')
        else:
            self.form_meta['title'] = _('new person')


class PersonDetailForm(ModelForm):
    extra = {}

    class Meta:
        model = PersonDetail
        exclude = '__all__'

    def __init__(self, *args, **kwargs):
        extra = kwargs.pop('extra')
        super(PersonDetailForm, self).__init__(*args, **kwargs)

        for i, question in enumerate(extra):
            self.fields['custom_%s' % i] = forms.CharField(label=question)

src/main/views.py
import json
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from accounts.forms import FacebookUserForm
from accounts.functions import get_or_create_user_with_fb_util, FOUND, CREATED
from event.functions import get_event_or_404_by_slug, get_fb_app_id
from event.models import Register, Ticket


def home(request):
    event = request.event
    if event:
        return show_event(request, event.nick)

    FB_APP_ID = get_fb_app_id()
    # return render_to_response('events/landing_event.html')
    return render(request, 'main/home.html', locals())


def show_event(request, event_nick):
    FB_APP_ID = get_fb_app_id()
    event = get_event_or_404_by_slug(event_nick)
    title = event.nick
    page_scheme = event.page_scheme
    scheme = page_scheme.scheme

    tickets = Ticket.objects.values('id', 'name').filter(event=event, is_active=True, is_public=True)

    event_parameters = {
        "tickets": list(tickets)
    }

    scheme = scheme.replace('TICKETS_JSON', json.dumps(event_parameters))
    return render(request, 'main/landing_event.html', locals())


@csrf_exempt
def register(request, event_nick):
    event = get_event_or_404_by_slug(event_nick)
    if not request.POST:
        raise Http404

    facebook_user_form = FacebookUserForm(request.POST)
    if not facebook_user_form.is_valid():
        raise 404
    response, user = get_or_create_user_with_fb_util(facebook_user_form=facebook_user_form)

    result = 0
    if response == FOUND or response == CREATED:
        ticket_id = request.POST.get('ticket_id')
        ticket = None
        if ticket_id:
            ticket = get_object_or_404(Ticket, pk=ticket_id)
        try:
            register = Register.objects.get(person=user.person, event=event)
            if ticket:
                register.ticket = ticket
                register.save()
            result = 2
        except Register.DoesNotExist:

            register = Register(person=user.person, event=event)
            if ticket:
                register.ticket = ticket
            register.save()
            result = 1
        except Register.MultipleObjectsReturned:
            result = 3

    return HttpResponse(result)


def filter_register(request, event_nick):
    event = get_event_or_404_by_slug(event_nick)

src/main/templates/main/blocks/footer.html
{% load static %}
{% load i18n %}
{% if footer != '' %}
    {% if footer == 'variant-footer-1' %}
        <footer class="classic">
            <div class="container">
                <div class="row">
                    <div class="col-sm-3">
                        <ul class="menu">
{#                            <li><a href="#">{% trans  'Press' %}</a></li>#}
{#                            <li><a href="#">{% trans  'Terms of service' %}</a></li>#}
{#                            <li><a href="#">{% trans  'About' %}</a></li>#}
{#                            <li><a href="#">{% trans  'Contact' %}</a></li>#}
                            <li><a class="inner-link back-to-top" href="#top">{% trans  'Back To Top' %}</a></li>
                        </ul>
                    </div>

                    <div class="col-sm-5">
                        <span class="lead color-heading">{% trans  'About' %} {{ event.nick }}</span>

                        <p>
                            {{ event.description }}
                        </p>
                    </div>

                    <div class="col-sm-4">
                        <ul class="contact-methods">
                            <li><i class="icon pe-7s-mail"></i><span>hello@meetup.net</span></li>
                            <li><i class="icon pe-7s-phone"></i><span>1800 382 372</span></li>
                            <li><i class="icon pe-7s-map-marker"></i><span>{{ event.address }}</span></li>
                        </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 text-center">
                        <ul class="social-profiles">
                            {% if event.twitter %}<li><a href="#"><i class="icon social_twitter"></i></a></li>{% endif %}
                            {% if event.facebook %}<li><a href="#"><i class="icon social_facebook"></i></a></li>{% endif %}
                            {% if event.dribbble %}<li><a href="#"><i class="icon social_dribbble"></i></a></li>{% endif %}
                            {% if event.instagram %}<li><a href="#"><i class="icon social_instagram"></i></a></li>{% endif %}
                            {% if event.googleplus %}<li><a href="#"><i class="icon social_googleplus"></i></a></li>{% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    {% elif footer == 'variant-footer-2' %}

        <footer class="short footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-3">
                        <span class="text-white">© Copyright 2015 eventus</span>
                    </div>

                    <div class="col-sm-9 text-right">
                        <ul class="menu">
{#                            <li><a href="#">{% trans  'Press' %}</a></li>#}
{#                            <li><a href="#">{% trans  'Terms of service' %}</a></li>#}
{#                            <li><a href="#">{% trans  'About' %}</a></li>#}
{#                            <li><a href="#">{% trans  'Contact' %}</a></li>#}
                            <li><a class="inner-link back-to-top" href="#top">{% trans  'Back To Top' %}&nbsp;<i
                                    class="icon pe-7s-angle-up-circle"></i></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </footer>
    {% endif %}
{% endif %}

src/main/templates/main/blocks/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    {#    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="all"/>#}
    <link href="{% static 'main/css/flexslider.min.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'main/css/elegant-icons.min.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'main/css/pe-icon-7-stroke.min.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'main/css/lightbox.min.css' %}" rel="stylesheet" type="text/css" media="all"/>
    {% if theme %}
        <link href="{% static 'main/variant/theme/css/'|add:theme %}" rel="stylesheet" type="text/css" media="all"/>
    {% else %}
        <link href="{% static 'main/variant/theme/css/theme-deepblue.css' %}" rel="stylesheet" type="text/css"
              media="all"/>
    {% endif %}
    <!--[if gte IE 9]>
        	<link rel="stylesheet" type="text/css" href="{% static 'main/css/ie9.css' %}" />
		<![endif]-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,300' rel='stylesheet' type='text/css'>
    <style>
        .btn-blue {
            background-color: #393EE1;
        }

        .btn-blue:hover {
            color: #fff;
            background: #3815e1;
        }

        select {
            color: #fff;
            background-color: #474747 !important;
        }
    </style>
</head>

src/main/templates/main/blocks/loader.html
<div class="loader">
    <div class="strip-holder">
        <div class="strip-1"></div>
        <div class="strip-2"></div>
        <div class="strip-3"></div>
    </div>
</div>

src/main/templates/main/blocks/navigation.html
{% load static %}
{% if nav != '' %}
    {% if nav == 'overlay' %}
        <nav class="overlay-nav">
    {% else %}
        <nav class="relative-nav">
    {% endif %}
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <img alt="Logo" class="logo logo-light" src="{% static 'main/img/logo-eventus-ligth.png' %}">
            <img alt="Logo" class="logo logo-dark" src="{% static 'main/img/logo-eventus-dark.png' %}">
        </div>

        <div class="col-md-10 text-right">
            <ul class="menu" style="margin-right: 32px;">
                <li><a class="inner-link" href="#about" target="default">Acerca de</a></li>
                {% if event.is_show_speakers %}
                    <li><a class="inner-link" href="#speakers" target="default">speakers</a></li>{% endif %}
                {% if event.is_show_presentations %}
                    <li><a class="inner-link" href="#schedule" target="default">schedule</a></li>{% endif %}
                {% if event.is_show_speakers %}
                    <li><a class="inner-link" href="#contact" target="default">directions</a></li>{% endif %}
                {% if event.is_show_speakers %}
                    <li><a class="inner-link" href="#subscribe" target="default">subscribe</a></li>{% endif %}
                {% if event.twitter %}
                    <li class="social-link">
                        <a href="{{ event.twitter }}"><i class="icon social_twitter"></i></a></li>{% endif %}
                {% if event.facebook %}
                    <li class="social-link">
                        <a href="{{ event.facebook }}"><i class="icon social_facebook"></i></a></li>{% endif %}
            </ul>
        </div>
    </div>
</div>
<div class="bottom-border"></div>
</nav>
{% endif %}

src/main/templates/main/blocks/register_form.html
{% load i18n %}

<form class="register email-form" action="{% url 'main:register' event.nick %}" method="post">
    {% csrf_token %}
    <input type="hidden" id="id_fbId" name="id">

    <div class="col-sm-6">
        <input class="form-name validate-required" type="text" placeholder="{% trans 'Name' %}"
               name="first_name" id="id_firstName"
               data-vip="{'buttonText':'Edit Placeholder Text','modalTitle':'Edit Placeholder Text','modalIntro':'Enter text you want the user to see when field is empty.','modalInputLabel':'Placeholder text:','selector':'input','attribute':'placeholder','refresh':'false'}">
    </div>
    <div class="col-sm-6">
        <input class="form-name validate-required" type="text" placeholder="{% trans 'Last Name' %}"
               name="last_name" id="id_lastName"
               data-vip="{'buttonText':'Edit Placeholder Text','modalTitle':'Edit Placeholder Text','modalIntro':'Enter text you want the user to see when field is empty.','modalInputLabel':'Placeholder text:','selector':'input','attribute':'placeholder','refresh':'false'}">
    </div>
    <div class="col-sm-6">
        <input class="form-email validate-email" type="text" placeholder="{% trans 'Email Address' %}"
               name="email" id="id_email"
               data-vip="{'buttonText':'Edit Placeholder Text','modalTitle':'Edit Placeholder Text','modalIntro':'Enter text you want the user to see when field is empty.','modalInputLabel':'Placeholder text:','selector':'input','attribute':'placeholder','refresh':'false'}">
    </div>
    <div class="col-sm-6">
        <input class="form-phone" type="text" placeholder="{% trans 'Phone Number' %}" name="phone"
               data-vip="{'buttonText':'Edit Placeholder Text','modalTitle':'Edit Placeholder Text','modalIntro':'Enter text you want the user to see when field is empty.','modalInputLabel':'Placeholder text:','selector':'input','attribute':'placeholder','refresh':'false'}">
    </div>
    <div class="col-sm-6">
        <div class="select-holder">
            <select class="form-selection" name="ticket_id" id="ticket_id">
                <option value="" selected="selected">{% trans 'select a ticket' %}</option>
            </select>
        </div>
    </div>

    <div class="col-sm-6">
        <input type="button" value="{% trans 'Register with facebook' %}" class="btn btn-blue btn-face" onclick="fb_login(showRegisterForm)">
        <input type="submit" value="{% trans 'Register Now' %}" class="btn btn-submit hide"
               data-vip="{'buttonText':'{% trans  'Edit Submit Button Text' %}','modalTitle':'{% trans  'Edit Submit Button Text' %}','modalIntro':'Enter text you want the user to see when field is empty.','modalInputLabel':'Submit button text:','selector':'input','attribute':'value','refresh':'false'}">

    </div>

    <div class="col-sm-12">
        <span>* We process using a 100% secure gateway</span>

        <div class="form-success"><span>Thank you, your registration has been received!</span></div>
        <div class="form-error"><span>Validation error, please check all fields</span></div>
    </div>
</form>

src/main/templates/main/blocks/scripts.html
{% load static %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
{#<script src="{% static 'main/js/bootstrap.min.js' %}"></script>#}
<script src="{% static 'main/js/skrollr.min.js' %}"></script>
<script src="{% static 'main/js/spectragram.min.js' %}"></script>
<script src="{% static 'main/js/flexslider.min.js' %}"></script>
<script src="{% static 'main/js/jquery.plugin.min.js' %}"></script>
<script src="{% static 'main/js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'main/js/jquery.countdown-es.js' %}"></script>
<script src="{% static 'main/js/lightbox.min.js' %}"></script>
<script src="{% static 'main/js/smooth-scroll.min.js' %}"></script>
<script src="{% static 'main/js/twitterfetcher.min.js' %}"></script>
<script src="{% static 'main/js/placeholders.min.js' %}"></script>
<script>var fbAppId = '{{ FB_APP_ID }}',eventSlug='{{ event.nick }}';</script>
<script src="{% static 'main/js/home/fb.extend.js' %}"></script>
<script src="{% static 'main/js/fb/fb.js' %}"></script>
<script src="{% static 'main/js/scripts.js' %}"></script>